theme: jekyll-theme-midnight
title: Welcome to my cybersecurity blog on GitHub.
description: I am a cybersecurity student currently learning about about networks and digital forensics. 
I will be updating this page with lessons learned in network security, forensics, cyberterrorism, and information security whenever I can.
